server:
  port: 8071

spring:
  application:
    name: config-server
  profiles:
    active: composite

  cloud:
    config:
      server:
        composite:
          - type: native
            search-locations: classpath:/config
        bootstrap: true