server:
  port: 8071

encrypt:
  key: secretkey

spring:
  application:
    name: config-server
  profiles:
    active: composite

  cloud:
    config:
      server:
        composite:
          - type: native
            search-locations: classpath:/config
#          - type: git
#            uri: https://github.com/BaoPhamm/practice-spring-cloud.git
#            searchPaths: licensingservice
        bootstrap: true
